name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relev
          
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.6'
          coverage: xdebug
                
      - name: Install dependencies with composer
        run: composer update --no-ansi --no-interaction --no-progress
  
      - name: Setup env
        run: cp .env.example .env
        
      - name: Generated Key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      
      - name: Setup Database On MySQL
        run: |
          sudo systemctl start mysql.service
          mysql -uroot -h127.0.0.1 -proot -e 'SET GLOBAL max_connections = 1000;'
          mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS testing_database;'
              
      - name: Run tests with phpunit/phpunit
        run: php artisan test --coverage-clover=coverage.xml
    
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        with:
          args:
            -Dsonar.projectKey=TSKGunGun_SonarCloudTest
            -Dsonar.organization=tskgungun
            -Dsonar.php.coverage.reportPaths=coverage.xml
